### ISSUE TITLE
Add support for linking to a shared/static library

### ISSUE THREAD

**Issue by HalosGhost** [DavyLandman/portable8439#1]
It would be pretty quick (only a few rules) to build a `.so` and/or a `.a` so that this could be easily packaged and used system-wide.

I even have a version of what would be required locally functioning already. Would you be interested in a PR to add support for building libraries to the `Makefile`?

Also, if you'd be interested in that, would you be interested in a general `Makefile` makeover to allow this to be more-easily packaged by distributions?

**Comment by DavyLandman** [comment]
Sure, very open for that.

As long as the current inclusion of just a single source file remains I'm okay with distributing binaries. (We'll have to take into account different architectures?)

**Comment by HalosGhost** [comment]
Solid! I'll do a bit of a makeover on the `Makefile` and open a PR. And, for sure, I'll ensure the single-c/single-h solution remains functional!
